INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('LAO','elicited','DTE Energy'),
	 ('RUS','guillotining','TransIP'),
	 ('LBY','vaduz','Vermaat Groep'),
	 ('NTZ','immensities','Safeway'),
	 ('ASM','outrigger','Mattel'),
	 ('KEN','extols','TOBROCO Machines'),
	 ('NGA','chauvinists','A-Mark Precious Metals'),
	 ('PNG','disprovable','Magellan Midstream Partners'),
	 ('MOZ','lateness','Temporary Works Design'),
	 ('GAB','nursed','247TailorSteel');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('COL','glisten','GEA Group'),
	 ('MLT','heathery','Popular'),
	 ('ATA','decommissioned','SeeCubic'),
	 ('CHN','supplement','Select Medical Holdings'),
	 ('UKR','winches','GlobalOrange'),
	 ('COD','woofer','Allekabels.nl'),
	 ('YMD','infiltrates','Parker-Hannifin'),
	 ('MAF','throttle','BayWa'),
	 ('BOL','eternal','L Brands'),
	 ('GTM','sagaciously','Hess');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('AUT','chances','Community Health Systems'),
	 ('ATN','heliosphere','Technicolor SA'),
	 ('PNG','landman','Bertelsmann'),
	 ('BHS','baluster','Michaels Cos.'),
	 ('BEL','celtic','W.R. Berkley'),
	 ('CUB','amorous','Public Service Enterprise Group'),
	 ('SUR','works','GEA Group'),
	 ('ANT','nutation','Xilinx'),
	 ('KIR','inheritable','Toys "R" Us'),
	 ('BWA','skate','Celanese');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('ASM','trek','Arcadis'),
	 ('CUB','interview','Lindenhaeghe Opleidingen'),
	 ('JEY','rescales','Batenburg Techniek'),
	 ('KEN','canines','BlackRock'),
	 ('PRK','gatecrashed','Belsimpel.nl'),
	 ('MDA','sympathised','Calpine'),
	 ('MLT','eyesore','Jibes'),
	 ('IRQ','salsa','Van Kooten Tuin en Buiten Leven'),
	 ('BWA','sexual','International Plywood'),
	 ('QAT','airliner','Broadcom');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('NHB','unideal','Wüsthof'),
	 ('MDA','unfeelingly','Meritor'),
	 ('NCL','germs','Pinnacle Entertainment'),
	 ('NRU','confessions','Vossloh'),
	 ('ARM','basked','Coca-Cola Enterprises'),
	 ('LSO','formulation','Essendant'),
	 ('GHA','paradigm','ISM eCompany'),
	 ('BRA','bear','Hagemeyer'),
	 ('CAN','epigraph','Target'),
	 ('BWA','interventionism','Stanley Black & Decker');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('WSM','hovered','TeKa Groep'),
	 ('BLM','weaned','Vitens-Evides International'),
	 ('JEY','rhesus','Danone'),
	 ('NPL','exhausted','Benchmark Electronics'),
	 ('REU','parthenogenesis','Nvidia'),
	 ('XXX','harridan','ASML'),
	 ('MLT','dissuades','WABCO Holdings'),
	 ('MYS','infrastructures','Paychex'),
	 ('AGO','adjusts','World Fuel Services'),
	 ('ATF','godfathers','HCC Insurance Holdings');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('UGA','matures','Lürssen'),
	 ('SLV','zaire','Behringer'),
	 ('LTU','restates','Dassault Systèmes'),
	 ('PCI','condescendingly','Advanced Micro Devices'),
	 ('RUS','jackinthebox','RCS Capital'),
	 ('SUR','retyped','Hama Photo'),
	 ('SXM','restrictively','NII Holdings'),
	 ('MAC','are','Lear'),
	 ('BMU','adiabatic','Kirby'),
	 ('PER','untried','Crane');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('DEU','extendability','WVH Gevelprojecten'),
	 ('ZWE','unregistered','Mutual of America Life Insurance'),
	 ('SPM','lifeblood','Witte Molen N.V.'),
	 ('AIA','overprinted','Your Professionals '),
	 ('ESH','epidemiologist','Oceanco'),
	 ('BVT','perverted','Talenter'),
	 ('ETH','disestablishment','Air France-KLM (Frans-Nederlands)'),
	 ('BHR','excommunicated','Schwan-Stabilo'),
	 ('PAK','carding','Columbia Sportswear'),
	 ('PAN','chug','Nordstrom');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('FSM','upsidedown','Centralparking.nl'),
	 ('MLT','hypothesiser','Ameren'),
	 ('MTQ','dignitaries','Orange S.A.'),
	 ('ESH','confident','Bed Bath & Beyond'),
	 ('TCA','countenancing','Calco Group'),
	 ('REU','phonemic','Bilfinger'),
	 ('DMA','norway','Advance Auto Parts'),
	 ('NOR','intentionality','Pep Boys-Manny, Moe & Jack'),
	 ('PAK','proclaim','CTOUCH Europe'),
	 ('PHL','exacerbation','Murphy USA');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('TWN','lagers','CenterPoint Energy'),
	 ('KIR','voicings','Werner Enterprises'),
	 ('VAT','spurge','Heijmans'),
	 ('KEN','stoics','Payper'),
	 ('TJK','horrendous','ScanSource'),
	 ('NFK','biographical','Antero Resources'),
	 ('ZAF','propagandists','Navistar International'),
	 ('ISL','moribundly','Sonic Automotive'),
	 ('MID','upbraiding','Carl Walther GmbH'),
	 ('VNM','centrifugal','Broadcom');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('SEN','bottleneck','Public Service Enterprise Group'),
	 ('SAU','disdainful','Harley-Davidson'),
	 ('SPM','braver','FysioSupplies'),
	 ('AFI','roan','Wavin'),
	 ('MDV','rheological','Wolverine World Wide'),
	 ('GTM','corporeal','Havenbedrijf Rotterdam'),
	 ('TCD','recursion','USG'),
	 ('DJI','skua','Lorillard'),
	 ('SUN','laminated','Arianespace'),
	 ('PAN','argument','Hubert Burda Media');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('UKR','roster','Marriott International'),
	 ('GUF','alienation','Quantic Dream'),
	 ('THA','unresisting','De Nederlandsche Bank'),
	 ('CMR','professorship','Symetra Financial'),
	 ('AZE','pleasures','USAA'),
	 ('KIR','modifying','Comcast'),
	 ('BVT','taps','Franklin Resources'),
	 ('NPL','peered','Tower International'),
	 ('GTM','infective','Kindred Healthcare'),
	 ('CHE','drizzly','Energy Transfer Equity');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('YMD','nabs','Sprouts Farmers Market'),
	 ('OMN','sniffing','American Eagle Outfitters'),
	 ('GEO','inca','Brabus'),
	 ('SGP','pursues','Computer Sciences'),
	 ('CXR','vow','NCR'),
	 ('VIR','opposition','Jacobs Engineering Group'),
	 ('NOR','assays','National Oilwell Varco'),
	 ('BYS','dearly','Tromp Group'),
	 ('GMB','conman','Dynegy'),
	 ('ATB','fusion','IDEX');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('BOL','explains','Oceaneering International'),
	 ('TCD','eschews','Country Financial'),
	 ('ISR','hillier','Van Iperen International'),
	 ('MSR','goldfish','Covestro'),
	 ('MDG','unwashed','Trumpf'),
	 ('SLB','cartoon','E.ON'),
	 ('MKD','qualities','Deutsche Messe'),
	 ('MYT','reformists','Booz Allen Hamilton Holding'),
	 ('GUF','addict','Criteo'),
	 ('ROU','heeding','ADT');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('SLE','manes','Gaumont'),
	 ('ATB','screeds','Devon Energy'),
	 ('FIN','larch','US Foods'),
	 ('PRK','unbiassed','Knipidee International'),
	 ('PYF','territories','Alliance Data Systems'),
	 ('AND','unjustifiably','Your Professionals '),
	 ('CPV','smallness','PBF Energy'),
	 ('BRA','ins','Der Spiegel'),
	 ('MTQ','asymptotes','Arthur J. Gallagher'),
	 ('ATB','taxonomical','Das Automotive Services');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('CPV','stumping','AECOM'),
	 ('SVK','spherically','Diezel'),
	 ('ERI','narcosis','Robert Half International'),
	 ('SYR','sincere','Ingram Micro'),
	 ('AZE','outhouse','Public Service Enterprise Group'),
	 ('TLS','ageings','Leidos Holdings'),
	 ('CXR','manufactured','Valero Energy'),
	 ('ETH','defenestration','Kelly Services'),
	 ('GUM','overestimate','Machinefabriek Houdijk'),
	 ('SUN','effrontery','Lafuma');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('HUN','fragments','Éditions Philippe Amaury'),
	 ('CCK','quadratures','Deutsche Messe'),
	 ('SKM','farriers','Fruity Line'),
	 ('SHN','magnetite','Nordzucker'),
	 ('BOL','chairman','Decom Technology People'),
	 ('TWN','yell','Linn Energy'),
	 ('GMB','hosta','Panera Bread'),
	 ('ABW','fang','Comerica'),
	 ('NOR','sop','FirstEnergy'),
	 ('COL','monomials','Genesis Energy');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('MDV','doubled','Sears Hometown & Outlet Stores'),
	 ('GRC','encroach','WorkFast'),
	 ('SOM','bantered','Regions Financial'),
	 ('WAK','scarified','Wittenstein'),
	 ('ROU','industriously','Molson Coors Brewing'),
	 ('SLV','percolators','Pernod Ricard'),
	 ('BRB','invocations','Scotts Miracle-Gro'),
	 ('KGZ','deflect','American Financial Group'),
	 ('BFA','badtempered','AECOM'),
	 ('HUN','discovered','Eisenberg Paris');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('GIB','sublime','Toll Brothers'),
	 ('GEO','awls','TNT N.V.'),
	 ('GRC','heartlessly','Tiffany'),
	 ('JOR','stiffens','Diebold'),
	 ('HMD','sjambok','Ryder System'),
	 ('UGA','quarrelsome','Sonoco Products'),
	 ('LBR','harmonium','Centene'),
	 ('PCN','barging','Wolverine World Wide'),
	 ('MRT','coldwar','ASM International (ASMI)'),
	 ('PNG','playwrights','General Mills');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('BOL','interpolated','Future Communication Consultants'),
	 ('KWT','washboard','Elastic'),
	 ('ATN','embroiled','MC2 France'),
	 ('SAU','hierarchical','Autoliv'),
	 ('IRN','radiocarbon','Leica Camera'),
	 ('SRB','payload','Meyer Werft'),
	 ('KAZ','undermining','Arcandor'),
	 ('PRI','lugubriously','Alcatel-Lucent'),
	 ('ZMB','genteelest','The Hyve'),
	 ('CPV','yonder','Martinair');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('RUS','detoured','Bax-shop.nl'),
	 ('GNQ','loamy','Humana'),
	 ('MNP','evocation','Pantry'),
	 ('GEO','ajar','Hama Photo'),
	 ('LBY','allowing','SCANA'),
	 ('CSK','role','Entergy'),
	 ('PNG','indistinctly','Aareal Bank'),
	 ('CXR','tested','Commerzbank'),
	 ('REU','richest','Reliance Steel & Aluminum'),
	 ('BMU','inordinately','TRW Automotive Holdings');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('SYC','basil','Pinnacle Entertainment'),
	 ('HKG','migratory','Edwards Lifesciences'),
	 ('VCT','opinionated','Delta Air Lines'),
	 ('GIB','suckling','Orangeworks Groep'),
	 ('SAU','heterologous','Anthem'),
	 ('SAU','quipper','Deutsche Telekom'),
	 ('ITA','cushioning','SunEdison'),
	 ('GBR','rifled','DHL Express'),
	 ('GRD','compensation','Reliance Steel & Aluminum'),
	 ('RWA','fisher','August Storck');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('UZB','trolling','Marriott International'),
	 ('TWN','epitomise','Ameriprise Financial'),
	 ('GUM','cellar','Skydreams'),
	 ('ECU','linkups','Elf Aquitaine'),
	 ('SYC','caddying','Weser Flugzeugbau'),
	 ('GNB','lizards','AccorHotels'),
	 ('IND','pierced','Ulla Popken'),
	 ('TTO','parentinlaw','Newfield Exploration'),
	 ('KHM','hallways','CF Industries Holdings'),
	 ('CCK','cupola','HollyFrontier');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('ATF','sandman','Vornado Realty Trust'),
	 ('KWT','evidenced','Rogam'),
	 ('DZA','casualty','International Flavors & Fragrances'),
	 ('PSE','colonic','Thor Industries'),
	 ('ATN','belted','Eutelsat'),
	 ('FLK','senile','Sebamed'),
	 ('IDN','accommodating','Metz'),
	 ('AND','masterminded','Van Ameyde Services'),
	 ('ZAF','tufted','Waterman'),
	 ('CRI','bailed','First American Financial');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('ARM','overplaying','Synopsys'),
	 ('XXX','impassivity','Integrys Energy Group'),
	 ('NRU','debarred','Ford Motor'),
	 ('LIE','pivots','Eastman Kodak'),
	 ('GUF','exploder','General Mills'),
	 ('FRA','corpuscular','Benecke-Kaliko'),
	 ('NRU','satisfactory','IT-Ernity Internet Services'),
	 ('CAF','politicians','Kar Auction Services'),
	 ('DEU','cheap','Abab'),
	 ('BDI','materialising','Nexeo Solutions Holdings');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('THA','noonday','Deutsche Post'),
	 ('GNB','redevelop','Nike'),
	 ('PRI','tackles','Smart'),
	 ('MKD','straitjacket','Getronics'),
	 ('BUR','deride','Warsteiner'),
	 ('SVK','gyrating','Archer Daniels Midland'),
	 ('GUF','punished','Nordzucker'),
	 ('DOM','chafes','Mapscape'),
	 ('SEN','granting','Alliance Holdings'),
	 ('GRC','distance','International Plywood');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('MWI','readability','Auto-Owners Insurance'),
	 ('MYS','labouring','DSW'),
	 ('ARM','relaunch','Oliver IT'),
	 ('ESH','disinter','Oneok'),
	 ('MLT','inhibit','Fresenius Medical Care'),
	 ('CIV','landslips','Vinci SA'),
	 ('BRB','crackers','Focke-Achgelis'),
	 ('ISR','joyriding','Groupe BPCE'),
	 ('ALA','aladdin','International Flavors & Fragrances'),
	 ('PHL','trademarks','4Kids');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('BLM','abandons','Miele'),
	 ('ZWE','barbecue','Ryerson Holding'),
	 ('VEN','myriad','Plexus'),
	 ('SPM','whizkids','Integrys Energy Group'),
	 ('WSM','dodo','Old Republic International'),
	 ('CSK','cushioned','Framatome'),
	 ('BUR','midwife','WESCO International'),
	 ('AGO','plague','Westlake Chemical'),
	 ('VDR','circles','FedEx'),
	 ('MYT','fortuitously','Saint-Gobain');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('WSM','cockatoo','Moog'),
	 ('PCZ','promulgating','Travelers Cos.'),
	 ('ZWE','hopper','Burlington Stores'),
	 ('NER','repurchase','Klöckner & Co SE'),
	 ('LVA','wending','Gardena'),
	 ('ATG','deserted','Nordzucker'),
	 ('EST','sawn','Lafuma'),
	 ('USA','invocation','BayWa'),
	 ('BEL','if','Alcatel-Lucent'),
	 ('CAF','terrace','Amerco');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('MAR','unmanly','EnerSys'),
	 ('QAT','stereotyping','SanDisk'),
	 ('AGO','lug','Re-on'),
	 ('TUR','mistyped','WVH Gevelprojecten'),
	 ('SWZ','strayed','FMC'),
	 ('IRN','duffel','Frontier Communications'),
	 ('TMP','tots','Havas'),
	 ('TUR','satisfactory','Integrys Energy Group'),
	 ('AFG','sleeveless','Urban Outfitters'),
	 ('SEN','circumstances','Mann+Hummel');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('BOL','isomorph','Temporary Works Design'),
	 ('JPN','sedate','Nu Skin Enterprises'),
	 ('PNG','ulcers','Das Automotive Services'),
	 ('LTU','lags','IMS Health Holdings'),
	 ('PCN','scrappy','BNP Paribas'),
	 ('TLS','gnarled','Linn Energy'),
	 ('AUT','detects','DHW Service'),
	 ('TJK','crews','Wolff & Müller'),
	 ('NTZ','godlike','Cameron International'),
	 ('EGY','damaging','Hugo Boss');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('OMN','infill','Post Holdings'),
	 ('VCT','leeks','Group9'),
	 ('BLZ','butterfat','4Kids'),
	 ('GTM','stalagmites','Toll Brothers'),
	 ('BFA','itching','Pepco Holdings'),
	 ('BRB','balaclava','Aldi'),
	 ('LTU','cliquey','Chiquita Brands International'),
	 ('LAO','unhooks','CHS'),
	 ('BUR','occurrence','D.R. Horton'),
	 ('BLZ','cortisone','Axell');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('CZE','liberalisation','Bavaria Film Studios'),
	 ('SUR','grandees','Hunter Douglas'),
	 ('IDN','chugging','Leggett & Platt'),
	 ('SLE','epidemics','Frontier Communications'),
	 ('ARM','conference','Talanx'),
	 ('VIR','commoner','Aaron''s'),
	 ('HKG','rouses','Event Rent'),
	 ('MAF','boldest','Pinnacle Foods'),
	 ('ESH','becomes','RSG Finance'),
	 ('SAU','operationally','Wirecard');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('MSR','pressurise','Hella'),
	 ('SOM','masterfully','Hubbell'),
	 ('IDN','gradings','Arcadis'),
	 ('MNP','necks','Microsoft'),
	 ('EGY','paddling','Brand New Day'),
	 ('DHY','analyses','Raymond James Financial'),
	 ('TMP','deists','TECO Energy'),
	 ('SJM','allied','Verizon'),
	 ('SKM','oddities','Eisenberg Paris'),
	 ('YMD','bequests','P4people HRM Services');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('USA','retrial','Salomon Group'),
	 ('MKD','cremations','Sysco'),
	 ('SYR','iterate','Bouwgroep Dijksma Draisma'),
	 ('CHL','summonsed','Thermo Fisher Scientific'),
	 ('NTZ','jaundiced','Axell'),
	 ('MCO','unimpressive','Robert Half International'),
	 ('NLD','sift','Cooper Tire & Rubber'),
	 ('MDG','drowning','Textron'),
	 ('BOL','pecking','ScanSource'),
	 ('USA','languidly','trivago');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('GUM','congratulate','Kien Facility Management'),
	 ('STP','civility','Airbus'),
	 ('COK','comers','Crane'),
	 ('CZE','attacking','Charles Schwab'),
	 ('NCL','truncheon','Hess'),
	 ('SYR','kerbside','CareFusion'),
	 ('ATF','baste','Diehl Metall'),
	 ('MLI','respect','HBL Online'),
	 ('MCO','thinness','RATP Group'),
	 ('LUX','soundproof','3M');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('YUG','undiagnosable','W.R. Grace'),
	 ('TUR','foreshadows','Aleris'),
	 ('LSO','kindle','Qurius'),
	 ('HRV','adores','UPS'),
	 ('FIN','sumptuously','American Electric Power'),
	 ('SSD','temporaries','Peugeot'),
	 ('CAF','multifarious','Arcandor'),
	 ('GMB','cedilla','Fannie Mae'),
	 ('YEM','fizzes','Bartosz ICT'),
	 ('NIC','gliding','Open Line');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('MDA','outshining','Bodan-Werft'),
	 ('MEX','dialysis','Randstad NV'),
	 ('IOT','undermined','Kansas City Southern'),
	 ('ARE','interpellation','KapStone Paper & Packaging'),
	 ('LTU','squeezy','DHL Express'),
	 ('GEL','internationalisation','EOG Resources'),
	 ('LBN','thermostat','Kaufland'),
	 ('LSO','procure','Covance'),
	 ('IND','chloroquine','Visa'),
	 ('PAK','smasher','KKR');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('AFI','nativity','YoungCapital'),
	 ('UKR','dispel','Vishay Intertechnology'),
	 ('BDI','nationalisation','Caterpillar'),
	 ('MLT','swabbed','TravelCenters of America'),
	 ('SYC','happened','Snecma'),
	 ('SCG','confiscations','ABN AMRO'),
	 ('BFA','shrills','Amica Mutual Insurance'),
	 ('FLK','rock','Newmont Mining'),
	 ('IRN','frogman','Gilead Sciences'),
	 ('LCA','psalm','SolarWorld');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('FLK','obituaries','Alliance Holdings'),
	 ('KIR','elementarily','Free'),
	 ('YEM','lithologies','GameStop'),
	 ('MHL','rejoined','Clean Harbors'),
	 ('CZE','leavers','Wintershall'),
	 ('SVK','quintuple','Chanel'),
	 ('ZAR','stepparents','Bank of New York Mellon Corp.'),
	 ('VCT','faucets','Vaude'),
	 ('SGS','washington','SunGard Data Systems'),
	 ('BHR','toileting','VWR');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('SKM','prefers','Covestro'),
	 ('LBY','bursars','International Flavors & Fragrances'),
	 ('MOZ','afar','Gandi'),
	 ('STP','quivering','Flexspecialisen'),
	 ('CYM','housings','Dominion Resources'),
	 ('MYS','swoops','Babcock & Wilcox'),
	 ('WSM','clinch','Tutor Perini'),
	 ('GEO','bloat','Decathlon Group'),
	 ('BLR','yesteryear','SunGard Data Systems'),
	 ('LBN','deflationary','Howaldtswerke-Deutsche Werft');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('POL','qualifiers','DHW Service'),
	 ('NLD','embraces','K+S'),
	 ('EST','unleashed','Schwan-Stabilo'),
	 ('CTE','head','Plexus'),
	 ('BHR','quickened','Partners Network'),
	 ('MAC','spotless','Schneider Electric'),
	 ('IRN','stations','Auto Union'),
	 ('SHN','congo','Ferrostaal'),
	 ('SGP','ravishes','Arburg'),
	 ('IRL','rubric','Synnex');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('SVK','stimuli','Buhrmann'),
	 ('RWA','whalebone','Gilead Sciences'),
	 ('CHL','gibbering','Axiall'),
	 ('PRY','peachy','Thales Group'),
	 ('RUS','sterilised','Mondelez International'),
	 ('COK','passionless','SABA'),
	 ('MCO','exteriors','Meritor'),
	 ('CZE','signors','Honeywell International'),
	 ('TTO','awoke','Brown-Forman'),
	 ('PCN','regular','Astrium');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('BHR','bedsit','Naval Group'),
	 ('LBR','dominantly','Harris'),
	 ('IOT','unblocking','Outerwall'),
	 ('ZAF','mixes','Amphenol'),
	 ('LTU','unlikelihood','Bodan-Werft'),
	 ('BRB','afire','Tesla Motors'),
	 ('KIR','tidily','WellCare Health Plans'),
	 ('LTU','virtue','Rituals'),
	 ('GMB','knottiest','Braun'),
	 ('CYM','vespers','First Solar');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('MCO','maintaining','Jibes'),
	 ('SGS','digital','Penny'),
	 ('WAK','acidophiles','TravelCenters of America'),
	 ('JPN','unsanitary','Saint-Gobain'),
	 ('ZAR','mismatching','PPG Industries'),
	 ('SLV','diesels','H&R Block'),
	 ('PHI','scolding','Avnet'),
	 ('DNK','samovar','Men''s Wearhouse'),
	 ('JAM','stuck','Fond of Bags'),
	 ('HVO','cortisone','Framatome');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('GIB','wheeling','Roper Technologies'),
	 ('ISR','markings','Universal Forest Products'),
	 ('ROU','classifier','Alaska Air Group'),
	 ('CHL','about','Lowe''s'),
	 ('TJK','logic','Marriott International'),
	 ('BUR','colourised','Melitta'),
	 ('IDN','commits','Terex'),
	 ('SPM','dressings','Booking.com'),
	 ('DEU','acquiescent','Celanese'),
	 ('BRN','eligibility','Itaq');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('BHS','eat','Audi'),
	 ('SXM','intensifying','Ingles Markets'),
	 ('GMB','sequent','CBS'),
	 ('CHL','gibbon','Vaude'),
	 ('GRD','discipleship','Pioneer Natural Resources'),
	 ('CXR','forced','Matthijs'),
	 ('ANT','adaptability','Biogen'),
	 ('BTN','mamba','Thor Industries'),
	 ('VUT','lymphomas','DVB Bank'),
	 ('TZA','vibrational','Elf Aquitaine');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('IOT','ambuscades','BayWa'),
	 ('NOR','rightwing','Meindl'),
	 ('LBY','numismatics','WAGO Kontakttechnik'),
	 ('CYM','breathless','trivago'),
	 ('MOZ','dishonesty','IT Staffing Groep'),
	 ('NLD','ignorable','Pinnacle Entertainment'),
	 ('SHN','jamb','Deutsche Börse'),
	 ('BRN','primaeval','Wavin'),
	 ('GGY','cabal','Newell Rubbermaid'),
	 ('PUS','coin','Michaels Cos.');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('VUT','unwraps','DaVita HealthCare Partners'),
	 ('MDG','strum','SABA'),
	 ('ALA','pored','Group 1 Automotive'),
	 ('SKM','sickbay','Westlake Chemical'),
	 ('DZA','cheater','Northrop Grumman'),
	 ('CSK','omega','AccorHotels'),
	 ('CXR','squawk','Sanofi'),
	 ('SEN','inhales','UnitedHealth Group'),
	 ('UMI','galloping','Moody''s'),
	 ('MLI','mispositioned','DirecTV');
INSERT INTO datprof.estante ("local",capacidade,categoria) VALUES
	 ('BHR','imposable','Atisreal'),
	 ('GLP','repertory','NuStar Energy'),
	 ('FXX','rustproof','Darling Ingredients'),
	 ('NTZ','condiments','Reemtsma'),
	 ('ALB','monolayer','YMOR E-Services'),
	 ('LIE','droopiest','Infineon Technologies'),
	 ('THA','pullover','Morgan Stanley'),
	 ('XXX','genitals','Graham Holdings'),
	 ('UMI','sedentary','TJX'),
	 ('CXR','repainted','Fastenal');
