DROP TABLE IF EXISTS "livro";

CREATE TABLE "livro" (
  id SERIAL PRIMARY KEY,
  titulo TEXT default NULL,
  autor varchar(255) default NULL,
  codigo_estante integer NULL
);

INSERT INTO livro (titulo,autor,codigo_estante)
VALUES
  ('dignissim tempor arcu. Vestibulum ut eros non enim commodo','Martena Chandler',1),
  ('velit. Aliquam nisl. Nulla eu neque','Mia Donaldson',2),
  ('nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse','Cecilia Franklin',3),
  ('tristique ac, eleifend','Seth Ellis',4),
  ('cursus','Latifah Dillard',5),
  ('libero. Integer in','Hedley Vaughn',6),
  ('suscipit, est ac facilisis facilisis, magna tellus faucibus','Jemima Acosta',7),
  ('risus a ultricies','Burke Dixon',8),
  ('vitae aliquam eros turpis non enim. Mauris quis turpis vitae','Elmo Gamble',9),
  ('non arcu.','Nadine Patel',10),
  ('risus','Guinevere Davis',11),
  ('Phasellus at augue id ante dictum cursus. Nunc mauris elit,','Isaac Good',12),
  ('semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis','Kane Pollard',13),
  ('lorem, auctor quis, tristique ac, eleifend','Kermit Pierce',14),
  ('ornare egestas ligula. Nullam','Jermaine Best',15),
  ('dignissim tempor arcu. Vestibulum','Wyatt Mcdonald',16),
  ('amet orci.','August Shaw',17),
  ('semper pretium neque. Morbi quis urna.','Abel Dickerson',18),
  ('neque tellus, imperdiet','Paula Bird',19),
  ('nec ante. Maecenas','Leila Guerra',20),
  ('pharetra nibh. Aliquam ornare, libero at','Sybil Stevens',21),
  ('interdum. Nunc sollicitudin commodo ipsum. Suspendisse','Marcia Hodges',22),
  ('Mauris blandit enim consequat','Neve Owens',23),
  ('tellus, imperdiet non, vestibulum nec, euismod in,','Davis Cooper',24),
  ('Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas','Sade Stephenson',25),
  ('luctus et ultrices posuere','Tashya Bailey',26),
  ('leo. Cras vehicula aliquet libero. Integer in magna. Phasellus','Ina Donovan',27),
  ('et nunc. Quisque','Martha Petersen',28),
  ('penatibus et magnis dis parturient','Reed Dodson',29),
  ('Nullam feugiat placerat','Linda Dennis',30),
  ('pharetra. Nam ac','Lacota Browning',31),
  ('blandit. Nam nulla magna, malesuada vel,','Hyatt Meyers',32),
  ('nibh. Quisque nonummy ipsum non arcu. Vivamus sit','Fredericka Kidd',33),
  ('ante bibendum ullamcorper. Duis cursus, diam','Hanae Singleton',34),
  ('et magnis dis parturient','Melvin Mcfarland',35),
  ('dolor, nonummy ac,','Bert Jenkins',36),
  ('orci sem eget massa. Suspendisse eleifend. Cras sed leo.','Buffy Spears',37),
  ('semper','Raven Donaldson',38),
  ('lectus. Cum','Libby Dodson',39),
  ('rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at,','Deanna Guerra',40),
  ('Suspendisse aliquet molestie','Joelle Kim',41),
  ('eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada','Carolyn Neal',42),
  ('magnis dis parturient montes, nascetur ridiculus','Gannon Walker',43),
  ('dis parturient','Candace Wheeler',44),
  ('Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat','Ulysses Walter',45),
  ('felis ullamcorper viverra.','Stephen Clayton',46),
  ('sapien. Cras dolor dolor, tempus non, lacinia at, iaculis','Lawrence Richard',47),
  ('nibh.','Freya Johnson',48),
  ('magna. Ut','Cedric Morales',49),
  ('ornare. Fusce mollis. Duis sit amet diam','Kimberly Tyler',50);
INSERT INTO livro (titulo,autor,codigo_estante)
VALUES
  ('vitae mauris sit amet lorem semper auctor. Mauris vel turpis.','Stacey Rhodes',51),
  ('eget, venenatis a, magna. Lorem ipsum dolor','Oren Ayers',52),
  ('enim non nisi. Aenean eget metus.','Paula Guy',53),
  ('Cras pellentesque. Sed dictum. Proin eget odio.','Cailin Ortega',54),
  ('ligula. Aenean','Xanthus Duffy',55),
  ('sagittis. Duis gravida. Praesent eu nulla at','Solomon Black',56),
  ('urna justo faucibus lectus, a sollicitudin orci sem eget massa.','Mechelle Marshall',57),
  ('eu augue','Rae Quinn',58),
  ('molestie. Sed id risus quis diam luctus lobortis. Class','Hadassah Wells',59),
  ('non massa non ante','Andrew Rodriquez',60),
  ('Nullam nisl. Maecenas','Josiah Cobb',61),
  ('auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare','Chastity Stout',62),
  ('nunc nulla vulputate','Zeph Whitfield',63),
  ('vulputate dui,','Steven Gay',64),
  ('lorem semper auctor. Mauris vel','Britanney Aguilar',65),
  ('ante. Maecenas mi','Robin Nunez',66),
  ('malesuada fames','Yoshi Valenzuela',67),
  ('ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin','Vivian Lancaster',68),
  ('elementum, lorem ut aliquam','Neville Schwartz',69),
  ('orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam','Yolanda Goff',70),
  ('ut quam vel sapien imperdiet ornare. In faucibus.','Daryl Kirk',71),
  ('auctor. Mauris vel turpis. Aliquam adipiscing','Lester Whitley',72),
  ('Cras lorem lorem, luctus','Yeo Clarke',73),
  ('sit amet ultricies sem magna nec quam.','Breanna Conley',74),
  ('eget tincidunt dui augue eu','Eliana Foley',75),
  ('consectetuer adipiscing','Kirby Garrett',76),
  ('dolor dapibus gravida. Aliquam tincidunt, nunc','Geraldine Nielsen',77),
  ('adipiscing, enim mi tempor','Fletcher Perkins',78),
  ('nibh','Rina Short',79),
  ('neque sed sem egestas blandit. Nam nulla','Otto Payne',80),
  ('vitae sodales nisi magna sed dui. Fusce aliquam,','Gemma Pugh',81),
  ('lorem semper auctor. Mauris','Lois Dunn',82),
  ('Vivamus euismod urna. Nullam lobortis quam a felis','Marvin Medina',83),
  ('enim.','Kevin Vinson',84),
  ('non,','Talon Ochoa',85),
  ('pellentesque eget, dictum placerat, augue. Sed molestie. Sed id','Austin Joyner',86),
  ('sit amet','Felix Pollard',87),
  ('vel est tempor bibendum. Donec felis orci, adipiscing','Lance Medina',88),
  ('augue scelerisque mollis. Phasellus libero mauris, aliquam','Yardley Vazquez',89),
  ('at pretium aliquet, metus urna convallis','Calvin Price',90),
  ('dignissim lacus. Aliquam','Ginger Hatfield',91),
  ('purus. Nullam scelerisque neque sed sem egestas blandit. Nam','Zorita Cabrera',92),
  ('nisl arcu iaculis enim, sit amet ornare lectus justo','Andrew Walters',93),
  ('cursus non, egestas a, dui. Cras pellentesque. Sed dictum.','Angelica Mueller',94),
  ('rutrum lorem','Asher Booth',95),
  ('venenatis a, magna.','Andrew Torres',96),
  ('est, congue a,','Larissa Ratliff',97),
  ('a, enim. Suspendisse aliquet, sem ut','Stephanie Brock',98),
  ('vitae mauris sit','Martha Romero',99),
  ('elit sed consequat auctor, nunc nulla vulputate','Herman Mcmahon',100);
INSERT INTO livro (titulo,autor,codigo_estante)
VALUES
  ('accumsan sed, facilisis vitae, orci. Phasellus','Lucas Douglas',101),
  ('dui, in sodales elit erat vitae risus. Duis a','Aline Reynolds',102),
  ('gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.','Austin Cortez',103),
  ('eu dui. Cum sociis natoque penatibus','Remedios Copeland',104),
  ('elit. Etiam','Hector Sykes',105),
  ('senectus et netus et malesuada fames ac turpis','Regina Aguilar',106),
  ('Duis risus odio, auctor vitae, aliquet nec, imperdiet nec,','Hadley Kennedy',107),
  ('tortor. Integer aliquam adipiscing','Abdul Sosa',108),
  ('hendrerit a, arcu. Sed et libero.','Chastity Dorsey',109),
  ('luctus et ultrices posuere','Scott Rosales',110),
  ('sapien molestie orci tincidunt adipiscing.','Unity Malone',111),
  ('non leo. Vivamus nibh dolor, nonummy ac, feugiat','Ivor Dillon',112),
  ('consequat purus. Maecenas libero est,','Paki Kirk',113),
  ('gravida non, sollicitudin a, malesuada','Bevis Price',114),
  ('sed dolor. Fusce mi lorem,','Plato Sims',115),
  ('eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas','Yoshi Blankenship',116),
  ('Aenean gravida nunc sed pede.','Phillip Wolf',117),
  ('orci. Phasellus dapibus','Colin Jennings',118),
  ('urna. Nullam lobortis','Reuben Hill',119),
  ('ornare lectus justo eu arcu. Morbi sit amet','Jennifer Hayes',120),
  ('cursus vestibulum. Mauris magna. Duis dignissim tempor arcu.','Ignatius Villarreal',121),
  ('arcu. Sed et libero. Proin','Wendy Mcclain',122),
  ('lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu,','Emerson Love',123),
  ('ligula elit, pretium et, rutrum non, hendrerit id, ante.','Inga Lynn',124),
  ('Fusce feugiat. Lorem ipsum dolor sit','Gary Byers',125),
  ('nulla ante, iaculis nec,','Fulton Simon',126),
  ('tincidunt vehicula','Winter Copeland',127),
  ('sit amet, consectetuer adipiscing elit. Etiam','Dawn Lynch',128),
  ('Nullam vitae diam. Proin dolor. Nulla semper tellus id','Florence Hatfield',129),
  ('Quisque libero lacus, varius','Malachi Middleton',130),
  ('consectetuer adipiscing elit.','Halee Clarke',131),
  ('enim','Francis Cross',132),
  ('ullamcorper,','Otto Randall',133),
  ('arcu. Vestibulum','Candace Mckay',134),
  ('per inceptos hymenaeos. Mauris ut quam vel sapien','Adele Chase',135),
  ('leo. Vivamus nibh dolor, nonummy ac,','Amelia Mccall',136),
  ('turpis. In condimentum. Donec at arcu.','Maggy Romero',137),
  ('metus eu erat semper rutrum. Fusce dolor quam, elementum','Laurel Clarke',138),
  ('eget magna. Suspendisse tristique neque','Donna Burris',139),
  ('ultrices posuere cubilia Curae Donec tincidunt. Donec','Hasad Craft',140),
  ('lectus pede, ultrices a,','Alexander Powers',141),
  ('odio. Phasellus at','Julie Pruitt',142),
  ('Curae Donec tincidunt. Donec vitae erat','Lacota Padilla',143),
  ('et libero. Proin mi.','Upton Lopez',144),
  ('dapibus ligula.','Caesar Caldwell',145),
  ('velit','Dillon Day',146),
  ('libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet','Karleigh Sandoval',147),
  ('quis arcu vel','Maia Noble',148),
  ('varius. Nam porttitor scelerisque neque.','Whoopi Stevenson',149),
  ('sed orci','Raphael Garrison',150);
INSERT INTO livro (titulo,autor,codigo_estante)
VALUES
  ('magna, malesuada vel,','Denton Holden',151),
  ('Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie','Montana Gonzales',152),
  ('a, enim. Suspendisse aliquet, sem ut','Martena Guerrero',153),
  ('eget tincidunt dui augue eu tellus. Phasellus elit pede,','Macey Whitehead',154),
  ('gravida. Praesent eu nulla at','Hakeem Farrell',155),
  ('erat vitae risus. Duis a','Martha Hooper',156),
  ('parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio','Raja Frederick',157),
  ('magna. Ut tincidunt orci quis lectus.','Uta Salas',158),
  ('Sed auctor odio a purus. Duis elementum,','Shad Morrison',159),
  ('porttitor interdum. Sed','Briar Fox',160),
  ('blandit mattis.','Evelyn Miles',161),
  ('lectus. Cum','Carly Robles',162),
  ('pharetra nibh. Aliquam ornare,','Marsden Edwards',163),
  ('vulputate eu, odio. Phasellus at augue id','Solomon Lawrence',164),
  ('turpis egestas. Fusce aliquet magna a neque.','Kay Shepard',165),
  ('elit, pretium et,','Blossom Kirk',166),
  ('lacinia. Sed congue,','Mari Nguyen',167),
  ('sed dui. Fusce','Hayden Wiggins',168),
  ('mauris sapien, cursus','Doris Tucker',169),
  ('arcu. Morbi sit amet massa. Quisque porttitor eros','Daphne Harvey',170),
  ('vel quam dignissim','Ulysses Dean',171),
  ('nibh dolor, nonummy','Kasimir Davis',172),
  ('nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis','Victor Bush',173),
  ('Aliquam nec enim.','Rinah Roach',174),
  ('fringilla euismod enim.','Ila Burns',175),
  ('arcu. Vestibulum ante ipsum primis','Merritt Greene',176),
  ('sem. Pellentesque','Skyler Henry',177),
  ('tempus, lorem fringilla','Stacey Mendoza',178),
  ('arcu. Sed eu nibh','Sean Clark',179),
  ('vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim.','Lilah Chavez',180),
  ('vitae erat vel pede','Scarlett Witt',181),
  ('eget metus eu erat semper rutrum. Fusce dolor','Burton Clements',182),
  ('sit amet, risus. Donec nibh enim,','Fiona Byers',183),
  ('libero et tristique pellentesque, tellus sem mollis dui, in','Wyoming Wade',184),
  ('blandit congue. In scelerisque scelerisque dui.','Renee Morin',185),
  ('semper erat, in consectetuer ipsum nunc','Melissa Guthrie',186),
  ('semper pretium neque. Morbi quis urna.','Armando Bright',187),
  ('nunc nulla vulputate dui, nec tempus mauris erat eget','Lyle Mccarty',188),
  ('iaculis odio. Nam interdum enim non nisi. Aenean eget','Germaine Dillon',189),
  ('in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu','James Delaney',190),
  ('tincidunt, neque vitae','Reece Porter',191),
  ('Curabitur vel lectus. Cum sociis natoque penatibus et','Thane Osborn',192),
  ('Cras vulputate velit','Summer Guy',193),
  ('lacus. Mauris non dui nec urna suscipit nonummy. Fusce','Yen Parks',194),
  ('orci','Nissim Gutierrez',195),
  ('Cras dolor dolor, tempus non, lacinia at,','Dai Wood',196),
  ('nisi sem semper erat, in consectetuer ipsum nunc','Lysandra Mcleod',197),
  ('a purus. Duis elementum, dui quis accumsan','Lila Conway',198),
  ('dui. Cum sociis natoque penatibus et magnis dis parturient','Rahim Brady',199),
  ('quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar','Hakeem Ruiz',200);
INSERT INTO livro (titulo,autor,codigo_estante)
VALUES
  ('dolor. Donec fringilla. Donec feugiat metus sit','Dana Foreman',201),
  ('tempus scelerisque,','Luke Ward',202),
  ('elementum sem, vitae aliquam eros turpis non enim. Mauris','Ronan Stanton',203),
  ('rutrum eu, ultrices sit amet, risus. Donec nibh enim,','Brandon Page',204),
  ('tempor','Zeus Webster',205),
  ('neque et nunc. Quisque ornare tortor','Alfreda Dudley',206),
  ('velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices.','Merrill Cline',207),
  ('aliquet, metus urna convallis erat, eget tincidunt dui','Cameron Powers',208),
  ('interdum. Sed','Mara Erickson',209),
  ('Mauris quis turpis vitae purus','Vincent Coffey',210),
  ('ultrices iaculis odio. Nam interdum enim non','Stephanie Russell',211),
  ('risus quis diam luctus lobortis. Class aptent','Lael Delacruz',212),
  ('Suspendisse non leo. Vivamus nibh','Claire Benton',213),
  ('pharetra. Nam ac nulla. In','Bruno Vargas',214),
  ('gravida. Aliquam tincidunt, nunc ac','Xenos Herman',215),
  ('mus. Donec dignissim','Sybil Avery',216),
  ('Nulla facilisi. Sed neque. Sed eget lacus. Mauris','Brock Carlson',217),
  ('risus. Morbi metus. Vivamus euismod urna. Nullam lobortis','Colorado Gilliam',218),
  ('facilisi.','Nicholas Estes',219),
  ('tellus. Phasellus elit pede, malesuada vel, venenatis','Britanni Carpenter',220),
  ('placerat, orci lacus vestibulum lorem, sit amet','Dexter Walter',221),
  ('Curabitur vel lectus. Cum sociis natoque penatibus et magnis','Wesley Vaughan',222),
  ('dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur','Fletcher Delaney',223),
  ('risus. Quisque libero lacus, varius et, euismod et, commodo','Kay Ferrell',224),
  ('mi tempor lorem, eget mollis lectus pede et risus.','Quamar Hill',225),
  ('Maecenas malesuada fringilla est. Mauris eu turpis. Nulla','Macon Mcintyre',226),
  ('et magnis dis','Galvin Rosa',227),
  ('luctus et','Salvador O''brien',228),
  ('dolor elit, pellentesque a, facilisis non,','Keefe Daugherty',229),
  ('varius ultrices, mauris ipsum porta elit, a','Drake Parrish',230),
  ('facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean','Isadora Rollins',231),
  ('massa. Mauris vestibulum,','Walter Joseph',232),
  ('consectetuer, cursus et, magna.','Chantale Mills',233),
  ('elementum at, egestas a, scelerisque sed,','Nola Harding',234),
  ('ligula. Aliquam erat volutpat.','Abdul Lott',235),
  ('congue, elit sed consequat auctor, nunc','Zenia Reyes',236),
  ('nibh. Donec est mauris,','Raven Mcguire',237),
  ('Phasellus elit pede, malesuada vel, venenatis vel, faucibus id,','Hammett Snider',238),
  ('montes, nascetur ridiculus mus. Proin vel','Rhonda Harrington',239),
  ('luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed','Rhiannon Farmer',240),
  ('natoque penatibus et magnis dis','Barrett Morgan',241),
  ('non, cursus non,','Kieran Keith',242),
  ('Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla','Tamara Rhodes',243),
  ('convallis in, cursus et,','Cynthia Frye',244),
  ('eleifend nec,','Jordan Bates',245),
  ('rutrum magna. Cras convallis convallis dolor.','Tatyana Stark',246),
  ('montes, nascetur ridiculus mus.','Irma Simmons',247),
  ('vulputate velit eu sem. Pellentesque','Joseph Mcconnell',248),
  ('Maecenas mi felis, adipiscing','Riley Acosta',249),
  ('diam at pretium aliquet,','Lucius Nielsen',250);
INSERT INTO livro (titulo,autor,codigo_estante)
VALUES
  ('molestie tellus. Aenean egestas hendrerit neque.','Celeste Yates',251),
  ('quam vel sapien imperdiet ornare. In faucibus.','Stacy Mendoza',252),
  ('sem. Pellentesque','Castor Barlow',253),
  ('ipsum non arcu. Vivamus sit amet risus.','Fuller Leblanc',254),
  ('imperdiet ullamcorper. Duis at lacus. Quisque purus sapien,','Dustin Kelly',255),
  ('amet, consectetuer adipiscing elit. Aliquam auctor, velit','Macy William',256),
  ('orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam','Arsenio Martinez',257),
  ('in faucibus orci luctus et ultrices posuere','Hiram Becker',258),
  ('congue turpis. In condimentum. Donec at','Kylan Aguilar',259),
  ('Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam','Yolanda Alvarado',260),
  ('mauris sapien, cursus','Malcolm Weaver',261),
  ('fringilla est.','Richard Mercado',262),
  ('semper tellus id nunc interdum feugiat.','Kermit Blevins',263),
  ('est ac facilisis facilisis, magna tellus faucibus leo,','Rogan Spears',264),
  ('lectus ante dictum mi,','Seth Watts',265),
  ('magna. Nam ligula elit, pretium et,','Ignacia Knowles',266),
  ('Proin dolor. Nulla semper','Cassandra Bradford',267),
  ('ante dictum mi, ac','Zena Kinney',268),
  ('Curae Donec tincidunt. Donec vitae','Irene Gill',269),
  ('lectus quis massa. Mauris vestibulum, neque sed','Kessie Roberson',270),
  ('amet lorem semper','Mohammad Small',271),
  ('tellus. Nunc lectus pede, ultrices','Chava Osborne',272),
  ('Nulla tincidunt, neque vitae semper egestas,','Samson Mccray',273),
  ('nunc, ullamcorper eu, euismod ac, fermentum','Silas Holder',274),
  ('in consequat','Lesley Booth',275),
  ('lectus. Cum sociis','Ramona Mccarthy',276),
  ('ullamcorper, velit in aliquet','Camden Hayes',277),
  ('Proin vel arcu eu odio tristique pharetra.','Marsden Hanson',278),
  ('tristique senectus et netus et malesuada fames ac turpis','Barrett Gardner',279),
  ('amet ultricies sem magna','Ila Mcdaniel',280),
  ('dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis','Nell Martin',281),
  ('mauris','Joelle Lowery',282),
  ('libero nec ligula consectetuer rhoncus. Nullam velit dui, semper','Theodore Gamble',283),
  ('ut cursus luctus, ipsum leo elementum sem, vitae','Paul Owens',284),
  ('tellus faucibus leo, in','Joelle Aguilar',285),
  ('accumsan interdum libero','Adrian Rush',286),
  ('hendrerit. Donec porttitor tellus non magna. Nam ligula','Carlos Ward',287),
  ('nec urna','Griffin Edwards',288),
  ('In faucibus. Morbi','Brenden York',289),
  ('habitant morbi tristique senectus et netus et malesuada fames ac','David Clayton',290),
  ('eget tincidunt','Armando Erickson',291),
  ('Duis sit amet diam eu dolor egestas rhoncus. Proin','Boris Randolph',292),
  ('risus. In','Constance Bray',293),
  ('Morbi quis urna. Nunc quis arcu vel quam dignissim','Kalia Ramsey',294),
  ('fringilla ornare placerat, orci lacus vestibulum lorem,','Kelsie Finley',295),
  ('ante bibendum ullamcorper. Duis','Ross Ruiz',296),
  ('nec tempus','Roth Hartman',297),
  ('nec ante. Maecenas mi felis, adipiscing','Asher Mooney',298),
  ('Curabitur dictum.','Raphael Sellers',299),
  ('pretium aliquet, metus urna convallis erat, eget','Clare Hahn',300);
INSERT INTO livro (titulo,autor,codigo_estante)
VALUES
  ('tincidunt, neque vitae semper egestas, urna justo faucibus lectus,','Amaya Carney',301),
  ('natoque penatibus et magnis','Nora Bates',302),
  ('sit amet ultricies sem magna nec quam. Curabitur','Sean Moses',303),
  ('mauris erat','Randall Noble',304),
  ('conubia nostra, per','Ishmael Watts',305),
  ('erat volutpat. Nulla facilisis. Suspendisse','Trevor Hatfield',306),
  ('fringilla cursus purus. Nullam scelerisque neque','Xanthus Osborne',307),
  ('nunc, ullamcorper eu, euismod ac, fermentum vel, mauris.','Rahim Barlow',308),
  ('volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat','Lance Atkins',309),
  ('euismod mauris eu elit. Nulla facilisi. Sed','Colby Hull',310),
  ('iaculis aliquet diam.','Laura Mcmillan',311),
  ('varius ultrices, mauris ipsum','Cheyenne Sims',312),
  ('ipsum cursus','Chase Head',313),
  ('ipsum primis in faucibus orci luctus et ultrices posuere','MacKensie White',314),
  ('et magnis dis','Carlos Harrell',315),
  ('condimentum. Donec at','Scott French',316),
  ('cubilia','Noble Mullen',317),
  ('in sodales elit erat','Chiquita Sykes',318),
  ('faucibus lectus, a sollicitudin orci sem eget massa.','Nero Rice',319),
  ('turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut','Fitzgerald Frazier',320),
  ('Aliquam nisl. Nulla eu','Ayanna Daugherty',321),
  ('pede ac','Ronan Castaneda',322),
  ('ut, nulla. Cras eu tellus eu augue porttitor','Kennan Sanford',323),
  ('egestas hendrerit neque. In','Tiger Marks',324),
  ('ultricies dignissim','Vivian Velez',325),
  ('eleifend vitae, erat.','Dane Macias',326),
  ('tristique aliquet. Phasellus fermentum convallis ligula. Donec','Kitra Meyer',327),
  ('consectetuer','Aretha Sheppard',328),
  ('erat vel pede blandit congue. In','Pascale Thomas',329),
  ('Sed eget','Dalton Chan',330),
  ('eget, ipsum. Donec','Dante Lloyd',331),
  ('feugiat. Sed','Ivana Schultz',332),
  ('ac','Suki Cochran',333),
  ('luctus sit amet, faucibus ut, nulla. Cras eu','Abdul Hoffman',334),
  ('hendrerit consectetuer, cursus et, magna. Praesent interdum','Karyn Gutierrez',335),
  ('eget lacus. Mauris non dui','Yoko Castaneda',336),
  ('senectus et netus et malesuada','Sierra Mclaughlin',337),
  ('at risus. Nunc ac sem ut dolor','Herrod Walton',338),
  ('Quisque purus sapien, gravida non, sollicitudin a, malesuada id,','Mechelle Oneal',339),
  ('Nullam suscipit, est ac','Gavin Mcclure',340),
  ('Cras interdum. Nunc sollicitudin','Melyssa Walters',341),
  ('libero. Proin sed turpis nec mauris blandit mattis. Cras eget','Griffin Alston',342),
  ('sem mollis dui, in sodales elit','Connor West',343),
  ('Donec feugiat metus sit amet ante.','Kitra Lang',344),
  ('fermentum fermentum arcu. Vestibulum ante','Nomlanga Clemons',345),
  ('risus. Morbi metus. Vivamus euismod','Tamekah Osborn',346),
  ('Etiam laoreet, libero','Illiana Rose',347),
  ('semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In','Quentin Rivas',348),
  ('dolor vitae','Conan William',349),
  ('faucibus ut, nulla.','Paula Macdonald',350);
INSERT INTO livro (titulo,autor,codigo_estante)
VALUES
  ('dictum augue malesuada malesuada. Integer id magna et ipsum cursus','Josiah Gutierrez',351),
  ('turpis. Aliquam','Kasper Moon',352),
  ('viverra. Maecenas iaculis aliquet diam. Sed diam','Christopher Howell',353),
  ('enim. Nunc ut erat. Sed nunc est, mollis non, cursus','Hunter Hodge',354),
  ('egestas lacinia. Sed congue, elit sed consequat auctor,','Barbara Burnett',355),
  ('vitae risus. Duis a','Kathleen Riley',356),
  ('metus urna convallis erat, eget tincidunt dui augue','Aaron Kelley',357),
  ('hendrerit neque. In ornare','Jason Spencer',358),
  ('id,','Kay Durham',359),
  ('Mauris quis turpis vitae purus gravida','Akeem Washington',360),
  ('ipsum','Zane Wilder',361),
  ('sit','Hiroko Bryan',362),
  ('laoreet, libero et tristique pellentesque, tellus sem mollis','Sylvia Meadows',363),
  ('Sed congue, elit sed consequat auctor, nunc nulla','Aileen Rivers',364),
  ('orci. Ut semper pretium neque.','Zeus Beard',365),
  ('velit justo nec ante. Maecenas','Patricia Burt',366),
  ('molestie in,','Dennis Duffy',367),
  ('neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu','Martena Hester',368),
  ('tincidunt orci quis lectus. Nullam suscipit, est','Tyler Whitley',369),
  ('dignissim. Maecenas ornare','Roary Terrell',370),
  ('consectetuer adipiscing elit. Aliquam auctor,','Iola Joyner',371),
  ('ut nisi a odio semper cursus. Integer mollis.','Leonard Bowers',372),
  ('quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus','Shay Jackson',373),
  ('massa. Suspendisse','Avye Sharpe',374),
  ('eget magna. Suspendisse tristique neque venenatis lacus. Etiam','Lila Roach',375),
  ('aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla','Tanner Ford',376),
  ('eleifend vitae, erat.','Rose Petersen',377),
  ('odio. Nam interdum enim','Dale Huber',378),
  ('Praesent eu nulla','Driscoll Byrd',379),
  ('ut eros','Jorden Mcpherson',380),
  ('ac nulla. In tincidunt congue turpis. In condimentum. Donec','Sebastian Miller',381),
  ('cursus non, egestas a, dui. Cras pellentesque. Sed','Daphne Mcpherson',382),
  ('magna. Nam ligula elit, pretium et, rutrum non, hendrerit id,','Tate Tran',383),
  ('at, nisi. Cum sociis natoque penatibus et magnis','Heather Morris',384),
  ('elit. Curabitur sed tortor.','Kelsey Mcgee',385),
  ('fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies','Cade Gilmore',386),
  ('rutrum eu, ultrices sit','Adena Ellis',387),
  ('Aenean massa. Integer vitae nibh. Donec est','Lars Albert',388),
  ('malesuada.','Tobias Dejesus',389),
  ('Donec dignissim magna a tortor. Nunc commodo','Kane Rutledge',390),
  ('diam. Sed diam lorem, auctor quis, tristique ac,','Eve Owen',391),
  ('Morbi','Dalton Francis',392),
  ('elit fermentum risus, at fringilla purus','Brynn Hudson',393),
  ('eget, venenatis a, magna. Lorem ipsum','Geraldine Hebert',394),
  ('lobortis augue scelerisque mollis.','Lucian Mcmillan',395),
  ('molestie. Sed id risus quis','Amal Gray',396),
  ('ipsum dolor','Travis Spence',397),
  ('lobortis risus. In mi pede, nonummy ut, molestie','Katelyn Wiley',398),
  ('urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus','Demetrius Bates',399),
  ('blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer','Erasmus Ray',400);
INSERT INTO livro (titulo,autor,codigo_estante)
VALUES
  ('iaculis odio. Nam interdum enim non nisi. Aenean eget','Belle Johns',401),
  ('fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus','Alden Sutton',402),
  ('dui, semper et, lacinia','Alan Sexton',403),
  ('nec,','Gay Wilcox',404),
  ('ut aliquam iaculis,','Leila Pruitt',405),
  ('eu, ultrices sit amet, risus. Donec nibh','Chester Hood',406),
  ('libero nec ligula consectetuer rhoncus. Nullam velit dui,','Beck Munoz',407),
  ('mauris. Morbi non','Deirdre Stark',408),
  ('gravida sagittis. Duis gravida. Praesent','Neville Swanson',409),
  ('ornare. In','Derek Rasmussen',410),
  ('cursus. Nunc mauris','Brennan Levy',411),
  ('magna. Ut tincidunt orci quis lectus.','Imani Zamora',412),
  ('Aliquam fringilla cursus purus. Nullam','Logan Schneider',413),
  ('tempus non, lacinia at, iaculis quis, pede.','Hope Powell',414),
  ('aliquet lobortis, nisi nibh lacinia','Hashim Hull',415),
  ('velit dui, semper','Charissa Jennings',416),
  ('non, feugiat nec, diam. Duis mi enim, condimentum','Damon Nicholson',417),
  ('sodales at, velit. Pellentesque ultricies','Erich Jones',418),
  ('magna, malesuada vel, convallis','Ezra Mclean',419),
  ('rutrum lorem ac','Lenore Rodriguez',420),
  ('posuere at, velit. Cras','Patricia Watkins',421),
  ('neque. Nullam ut nisi a odio semper','Daryl Holder',422),
  ('sit amet, dapibus id, blandit at, nisi.','Gwendolyn Houston',423),
  ('sociis','Noble Wise',424),
  ('enim.','Deanna Aguirre',425),
  ('pede ac urna.','Chadwick Petty',426),
  ('eleifend, nunc risus varius orci, in consequat','Brynn Curtis',427),
  ('commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus','Garth Kelly',428),
  ('nascetur ridiculus mus.','Ramona Barrett',429),
  ('pulvinar arcu et pede. Nunc','Aladdin Frost',430),
  ('urna justo faucibus lectus, a sollicitudin orci sem eget','Uta Skinner',431),
  ('Vivamus nibh dolor,','MacKenzie Hoffman',432),
  ('ante dictum mi, ac mattis velit justo nec ante.','Lesley Bauer',433),
  ('ornare, facilisis eget,','Sophia Bullock',434),
  ('interdum. Sed auctor odio a','Drake Odom',435),
  ('nulla','Joshua Blanchard',436),
  ('pede et risus. Quisque libero lacus, varius','Miriam Carrillo',437),
  ('risus a ultricies','Wang Battle',438),
  ('Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae','Eagan Clarke',439),
  ('et','Avye Casey',440),
  ('bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus','Joshua Hobbs',441),
  ('facilisi.','Logan Walter',442),
  ('Mauris blandit enim consequat','Maite Ward',443),
  ('lacus. Ut nec urna et','Keefe Villarreal',444),
  ('vitae diam. Proin dolor. Nulla semper tellus','Mannix Barron',445),
  ('elit, pellentesque','Yoshi Guthrie',446),
  ('odio. Etiam ligula tortor,','Phillip Bailey',447),
  ('varius. Nam porttitor scelerisque','Kim Sloan',448),
  ('nisi magna sed dui. Fusce aliquam, enim nec tempus','Anastasia Taylor',449),
  ('vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy','Benjamin Cummings',450);
INSERT INTO livro (titulo,autor,codigo_estante)
VALUES
  ('ullamcorper, nisl arcu','Keith Snyder',451),
  ('ipsum non arcu.','Alea Donaldson',452),
  ('Integer tincidunt','Kermit Mclaughlin',453),
  ('fringilla est. Mauris eu turpis. Nulla aliquet. Proin','Omar Steele',454),
  ('ut lacus.','Cooper Fletcher',455),
  ('consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus','Maya Keith',456),
  ('faucibus leo, in lobortis tellus justo sit','Oliver Townsend',457),
  ('Sed dictum. Proin eget odio.','Destiny Hale',458),
  ('non, feugiat','Addison Newman',459),
  ('dictum. Phasellus in','Priscilla Jones',460),
  ('elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut','Cody Mclaughlin',461),
  ('lectus ante dictum mi, ac mattis velit justo','Cullen Mckinney',462),
  ('justo','Sean Miller',463),
  ('et magnis dis parturient montes, nascetur ridiculus mus. Proin','Harding Petty',464),
  ('in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum','Patience Mckenzie',465),
  ('Maecenas malesuada fringilla est. Mauris eu turpis. Nulla','Baker Nieves',466),
  ('Cras eget nisi dictum augue malesuada malesuada. Integer','Orla Salazar',467),
  ('mi lorem,','Richard Snow',468),
  ('tincidunt aliquam arcu. Aliquam','Todd Sellers',469),
  ('amet,','Amity Greer',470),
  ('Aliquam tincidunt, nunc ac mattis','Mollie Pace',471),
  ('auctor, velit eget laoreet','Driscoll Nash',472),
  ('per inceptos hymenaeos. Mauris','Raymond Weaver',473),
  ('ut aliquam iaculis, lacus pede sagittis augue,','Chelsea Vance',474),
  ('sodales elit erat vitae risus. Duis a mi fringilla','Rhiannon Battle',475),
  ('pellentesque','Hanae Cooper',476),
  ('ligula. Aenean','Daquan Guzman',477),
  ('at auctor ullamcorper, nisl arcu iaculis','Juliet Hale',478),
  ('pharetra ut, pharetra','Wendy Garner',479),
  ('malesuada augue ut lacus. Nulla','Benjamin Cortez',480),
  ('eget, venenatis a, magna. Lorem ipsum dolor sit','Edan Mcdaniel',481),
  ('dolor','Cara Bryant',482),
  ('elementum','Mariko Carver',483),
  ('eget, ipsum. Donec sollicitudin adipiscing ligula.','Beau Hebert',484),
  ('eros non enim commodo','Matthew Flynn',485),
  ('non quam. Pellentesque habitant morbi tristique senectus et','Flynn Parks',486),
  ('tellus non magna. Nam','Autumn Ballard',487),
  ('egestas. Aliquam nec enim. Nunc ut erat.','Lamar Brewer',488),
  ('Duis volutpat nunc sit amet','Hunter Sweet',489),
  ('pellentesque eget, dictum placerat, augue.','Kamal Velasquez',490),
  ('fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra','Philip Shannon',491),
  ('cursus. Nunc mauris elit, dictum eu, eleifend nec,','Kelsey Haley',492),
  ('Maecenas mi felis,','Claire Blackburn',493),
  ('quam vel sapien','Hakeem Long',494),
  ('imperdiet dictum magna. Ut','Mira Mcguire',495),
  ('tincidunt, neque vitae semper egestas, urna','Dominique Peterson',496),
  ('dolor vitae','Tashya Salazar',497),
  ('nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod','Conan Hughes',498),
  ('Fusce dolor','Abra Cantrell',499),
  ('euismod','Elton Clarke',500);
